[versions]
agp = "8.6.0"
junit = "4.13.2"
appcompat = "1.6.1"
ads-identifier = "18.0.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
adsidentifier = { group = "com.google.android.gms", name = "play-services-ads-identifier", version.ref = "ads-identifier" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

